### ISSUE TITLE
Asm parser CPU/memory hungry

### ISSUE THREAD

**Issue by xor2003** [igordejanovic/parglare#120]
* parglare version:0.12.0
* Python version: 3.7.4
* Operating System:Windows 10 x86_64

### Description

Comilation eats a lot of CPU and memory.
I don't know how to troubleshoot.

### What I Did

EBNF:
[_masm61.zip](https://github.com/igordejanovic/parglare/files/4799580/_masm61.zip)

```
pglr --no-colors --debug  compile _masm61.pg  
```

**Comment by igordejanovic** [comment]
Thank for the report. Your grammar is huge and has a huge number of conflicts. It will be a good input for optimization. Will investigate in the following days.

**Comment by xor2003** [comment]
Maybe some additional diagnostics possible to add?

**Comment by igordejanovic** [comment]
Definitely will need some tracing info during table construction.

**Comment by igordejanovic** [comment]
I've added debug printouts during table construction and removed some unnecessary string constructions. It now compiles.

BTW, your grammar can be optimized in this part:
```
decNumber
  :decdigit+
  ; 
digits
  :decdigit+| digits hexdigit
  ; 
...
radixOverride
  : 'H' | 'O' | 'Q' | 'T' | 'Y'
  ; 
decdigit
  : '0' | '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9'
  ; 
hexdigit
  : 'A' | 'B' | 'C' | 'D' | 'E' | 'F'
  ; 
letter : "A" | "B" | "C" | "D" | "E" | "F" | "G"
       | "H" | "I" | "J" | "K" | "L" | "M" | "N"
       | "O" | "P" | "Q" | "R" | "S" | "T" | "U"
       | "V" | "W" | "X" | "Y" | "Z" | "a" | "b"
       | "c" | "d" | "e" | "f" | "g" | "h" | "i"
       | "j" | "k" | "l" | "m" | "n" | "o" | "p"
       | "q" | "r" | "s" | "t" | "u" | "v" | "w"
       | "x" | "y" | "z" | "_";
id: letter
| id letter
| id decdigit;
``` 

You could use regex matches for these rules instead of using the parser to do the parsing of lexemes (id, hexdigit,  decdigit, radixOverride). By making regexes for these the number of states will be reduced, table construction and the parsing itself will be faster.

**Comment by xor2003** [comment]
Thank you!
Is it much better now.
