### ISSUE TITLE
Wrong associativity behavior

### ISSUE THREAD

**Issue by survivorm** [igordejanovic/parglare#22]
* parglare version: 0.4.1
* Python version: Python 2.7.14 (default, Jan  5 2018, 10:41:29) 
[GCC 7.2.1 20171224] on linux2

* Operating System: Arch Linux

### Description

simple calculator test
Grammar:
STMT :  STMT ADDOP STMT {left, 1}
     |  STMT MULOP STMT {left, 2}
     | "(" STMT ")" | NUMBER;
ADDOP : "+" | "-";
MULOP : "*"|"/"; 
NUMBER: /\d+(\.\d+)?/;
input:
1 + 2 / (3 - 1 + 5)

### What I Did

from parglare import Grammar
from parglare import Parser

grammar = Grammar.from_file("calc_pg.pg")
parser = Parser(grammar)
print('1 + 2 / (3 - 1 + 5)')
result = parser.parse('1 + 2 / (3 - 1 + 5)')
            
print(result)
1 + 2 / (3 - 1 + 5)
['1', u'+', ['2', u'/', [u'(', ['3', u'-', ['1', u'+', '5']], u')']]]

WTF? Why's 1 + 5 is done before  3 - 1?
I've tried {left, 1} and {1, left} - no better
Classic grammar works better
STMT : TERM | STMT ADDOP TERM ;
TERM : FACTOR | FACTOR MULOP FACTOR ;
FACTOR : "(" STMT ")" | NUMBER;
ADDOP : "+" | "-";
MULOP : "*"|"/"; 
NUMBER: /\d+(\.\d+)?/;

program output:
1 + 2 / (3 - 1 + 5)
['1', u'+', ['2', u'/', [u'(', [['3', u'-', '1'], u'+', '5'], u')']]]

**Comment by igordejanovic** [comment]
Good catch.

The right solution would be to give both statements production and operator terminals the same priority.
Something like this:
```
STMT : STMT ADDOP STMT {left, 1}
     | STMT MULOP STMT {left, 1}
     | "(" STMT ")" | NUMBER;
ADDOP : "+" {1}
      | "-" {1};
MULOP : "*" {2}
      | "/" {2};
NUMBER: /\d+(.\d+)?/;
```
But, unfortunately, that doesn't work due to ambiguity between Non-terminal and Terminal parse in the part of the grammar of the form `ADDOP: "+" {1}...`. The parser needs more than 1 lookahead to decide if this is Terminal or Non-Terminal.

Futhermore, #17 will provide less typing when you have e.g. same priority in all production of a rule. 
This will enable something like this:
```
STMT {left}: STMT ADDOP STMT {1}
           | STMT MULOP STMT {2}
STMT: "(" STMT ")" | NUMBER;
ADDOP {1}: "+" | "-";
MULOP {2}: "*" | "/";
NUMBER: /\d+(.\d+)?/;
```


I'll work on fixing this.

In the mean time, a workaround is to use directly terminal operators in STMT definitions.
```
STMT : STMT "+" STMT {left, 1}
     | STMT "-" STMT {left, 1}
     | STMT "*" STMT {left, 2}
     | STMT "/" STMT {left, 2}
     | "(" STMT ")" | NUMBER;
NUMBER: /\d+(.\d+)?/;

```

**Comment by survivorm** [comment]
So, the problem is with That ADDOP/ MULOP are rules itself?
So, if they're made simple statements, problem is solved?

**Comment by igordejanovic** [comment]
The problem is that parglare doesn't really know anything about associativity and operators. :)

Keyword `left` is just a synonym of `reduce` (see note in [this section](http://www.igordejanovic.net/parglare/disambiguation/#associativity)) which means "if you are at this production and token ahead if of the same priority use reduce instead of shift" which is essentially a behaviour that leads to left associativity for operators of the same priority.
Priorities are honoured first.

Since ADDOP and MULOP are separate rules with two productions each and their priority is not explicitly set it is given a default priority of 10 which is higher than priority set for STMT productions.
This means that the token ahead will always have a greater priority and lead to shift, .e.g right associativity.

Yes. If you are use operator terminal inline as in the last example, than everything will work as expected as the terminals will be given the same priority of the STMT production.

Second example is something that will be preferred way to do it when #17 is done.

Hope this helps.

**Comment by survivorm** [comment]
Thanks. That was more a research for an article on parsing in general, but it is still interesting info.

**Comment by igordejanovic** [comment]
With the introduction of #34 first suggested variant works. Terminals should be written in separate section like:
```
STMT : STMT ADDOP STMT {left, 1}
     | STMT MULOP STMT {left, 1}
     | "(" STMT ")" | NUMBER;
ADDOP : "+" {1}
      | "-" {1};
MULOP : "*" {2}
      | "/" {2};

terminals
NUMBER: /\d+(.\d+)?/;
```

Please see [the tests](https://github.com/igordejanovic/parglare/blob/master/tests/func/regressions/test_issue_22_wrong_associativity_behaviour.py).

**Comment by survivorm** [comment]
Great, thanks!

**Comment by igordejanovic** [comment]
Just for completeness, #17 is implemented on `master` so now the grammar can be written in a simpler form:
```
STMT {left}: STMT ADDOP STMT {1}
           | STMT MULOP STMT {2};
STMT: "(" STMT ")" | NUMBER;
ADDOP {1}: "+" | "-";
MULOP {2}: "*" | "/";

terminals
NUMBER: /\d+(.\d+)?/;

``` 

[Here](https://github.com/igordejanovic/parglare/blob/master/tests/func/regressions/test_issue_22_wrong_associativity_behaviour.py) are the tests. The docs will be updated in the next few days.
